---
apiVersion: batch/v1
kind: Job
metadata:
  name: &name set-pyrus-setupparam
  labels: &selector
    app: *name
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: setup-complite
          image: simplygoodsoftware/k8s-waits
          imagePullPolicy: IfNotPresent
          command: [ "ls" ]
