apiVersion: v2
name: pyrus-datacenter
description: |
  Pyrus datacenter instalation v2 for Kubernetes
  
  ## Install 
  helm -n pyrus install --dependency-update --create-namespace pyrus-datacenter ./pyrus-datacenter
  
  ## Upgrade
  helm -n pyrus upgrade pyrus-datacenter ./pyrus-datacenter --reset-values
  
  ## Uninstall
  helm -n pyrus uninstall pyrus-datacenter

maintainers:
  - name: Simply Good Software Inc.

## application(templates and versioning)/library(develop utils and functions without templates)
type: application

## Helm chart version
version: 2.0.34

## Pyrus default version
appVersion: "latest"

dependencies:
  - name: nats
    version: "1.1.9"
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nats.enabled

  - name: postgres-operator
    version: "1.8.2"
    repository: "https://simplygoodsoftware.github.io/pyrus-datacenter-k8s"
    condition: postgresql.enabledHA
    alias: postgresql
