{{- if .Values.imagePullSecrets }}
apiVersion: v1
data:
  .dockerconfigjson: {{ include "pyrus-datacenter.docker-pyrus-cred" . | fromYaml | toJson | b64enc }}
kind: Secret
metadata:
  name: docker-pyrus-cred
type: kubernetes.io/dockerconfigjson
{{- end }}

