{{- $rl := .Release }}
{{- $vl := .Values }}
{{- $fl := .Files }}
{{- range $secretName := $vl.importWebSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ print "certs/" $secretName ".crt" | $fl.Get | b64enc }}
  tls.key: {{ print "certs/" $secretName ".key" | $fl.Get | b64enc }}
  tls.pem: {{ print "certs/" $secretName ".pem" | $fl.Get | b64enc }}
{{- end }}
