---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-variables
data:
{{- if not (hasKey $.Values "connectionStringsCreds") }}
{{-   range $key, $vl := ($.Files.Get ($.Values.connectionStringsPath | default "configs/connectionStrings.yaml") | fromYaml) }}
  {{ $key }}: {{ $vl | toYaml | indent 4 }}
{{-   end }}
{{- else if hasKey $.Values "connectionStringsCreds" }}
{{-     range $key, $vl := $.Values.connectionStringsCreds }}
  {{ $key }}: {{ $vl | toYaml | indent 4 }}
{{-   end }}
{{- end }}
