---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-variables
  annotations:
    checksum/config: {{ $.Files.Get "configs/connectionStrings.yaml" | sha256sum }}
data:
  {{-   range $key, $vl := ($.Files.Get "configs/connectionStrings.yaml" | fromYaml) }}
  {{ $key }}: {{ $vl | toYaml | indent 4 }}
  {{-   end }}
