---
apiVersion: batch/v1
kind: Job
metadata:
  name: &name set-pyrus-setupparam
  labels: &selector
    app: *name
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "-5"
    #helm.sh/hook-delete-policy: hook-failed
spec:
  activeDeadlineSeconds: 1200
  template:
    spec:
      restartPolicy: OnFailure
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: docker-pyrus-cred
{{- end }}
      initContainers:
        - name: depends-on
          image: simplygoodsoftware/k8s-waits
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          command: 
            - wait_endpoints
            - {{ .Release.Namespace }}/endpoints/pyrus-postgresql
            - {{ .Release.Namespace }}/endpoints/pyrus-elastic
            - {{ .Release.Namespace }}/endpoints/pyrus-logs-pgsql

{{- if not (hasKey .Values.standalonePostgreSQLBackup "RESTORE_NAME")  }}

        - name: setup-create-db
          image: simplygoodsoftware/{{ .Values.imageDevPrefix }}pyrus-setup
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          args: [
            "--create", "--skip",
            "--email", "{{ .Values.pyrusSetupParam.adminEmail }}",
            "--adminpassword",  "{{ .Values.pyrusSetupParam.adminPass }}"
            ]
{{- end }}

        - name: start-change-tracking
          image: simplygoodsoftware/{{ .Values.imageDevPrefix }}pyrus-setup
          imagePullPolicy: IfNotPresent
          args:
            - -ct
            - --start

        - name: setup-elastic-index-it
          image: simplygoodsoftware/pyrus-elastic-console
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          args:
            - -it

        - name: setup-elastic-index-ip
          image: simplygoodsoftware/pyrus-elastic-console
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          args:
            - -in

        - name: setup-elastic-index-ic
          image: simplygoodsoftware/pyrus-elastic-console
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          args:
            - -ic

        - name: setup-elastic-index-ip2
          image: simplygoodsoftware/pyrus-elastic-console
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          args:
            - -ip

{{- if hasKey .Values.standalonePostgreSQLBackup "RESTORE_NAME"  }}

        - name: setup-administrator-account
          image: simplygoodsoftware/{{ .Values.imageDevPrefix }}pyrus-setup
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          args: [
            "--setadmin",
            "--email", "{{ .Values.pyrusSetupParam.adminEmail }}",
            "--adminpassword",  "{{ .Values.pyrusSetupParam.adminPass }}"
            ]

        - name: setup-elastic-index-rt
          image: simplygoodsoftware/pyrus-elastic-console
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          args:
            - -rt

        - name: setup-elastic-index-wgall
          image: simplygoodsoftware/pyrus-elastic-console
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          args:
            - -wgall

        - name: setup-elastic-index-wcall
          image: simplygoodsoftware/pyrus-elastic-console
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          args:
            - -wcall

        - name: setup-elastic-index-wpall
          image: simplygoodsoftware/pyrus-elastic-console
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          args:
            - -wpall

        - name: setup-elastic-index-wnall
          image: simplygoodsoftware/pyrus-elastic-console
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          args:
            - -wnall
{{- end }}

{{- if .Values.pyrusSetupParam.s3 }}
        - name: setup-s3-storrage-1
          image: simplygoodsoftware/{{ .Values.imageDevPrefix }}pyrus-setup
          imagePullPolicy: IfNotPresent
          args: [ "--setup", "-id", "9900151", "-v", "{{ .Values.pyrusSetupParam.s3.keyId }}"]

        - name: setup-s3-storrage-2
          image: simplygoodsoftware/{{ .Values.imageDevPrefix }}pyrus-setup
          imagePullPolicy: IfNotPresent
          args: ["--setup", "-id", "9900152", "-v", "{{ .Values.pyrusSetupParam.s3.secretKey }}"]

        - name: setup-s3-storrage-3
          image: simplygoodsoftware/{{ .Values.imageDevPrefix }}pyrus-setup
          imagePullPolicy: IfNotPresent
          args: ["--setup", "-id", "9900153", "-v", "{{ .Values.pyrusSetupParam.s3.buket }}"]

        - name: setup-s3-storrage-4
          image: simplygoodsoftware/{{ .Values.imageDevPrefix }}pyrus-setup
          imagePullPolicy: IfNotPresent
          args: [ "--setup", "-id", "9910002", "-v", "{{ .Values.pyrusSetupParam.s3.region }}" ]

        - name: setup-s3-storrage-5
          image: simplygoodsoftware/{{ .Values.imageDevPrefix }}pyrus-setup
          imagePullPolicy: IfNotPresent
          args: [ "--setup", "-id", "9910004", "-v", "{{ .Values.pyrusSetupParam.s3.useit }}"]
{{- end}}

        - name: setup-license-variables
          image: simplygoodsoftware/{{ .Values.imageDevPrefix }}pyrus-setup
          imagePullPolicy: IfNotPresent
          args: ["--setup", "-id", "100000", "-v", "{{ .Values.pyrusSetupParam.license }}"]

        - name: setup-domain-name
          image: simplygoodsoftware/{{ .Values.imageDevPrefix }}pyrus-setup
          imagePullPolicy: IfNotPresent
          args: ["--setup", "-id", "100001", "-v", "{{ first (first (index .Values "values-ingress-dir").tls).hosts }}"]

{{- if .Values.imageDevPrefix }}
        - name: update-database-for-dev
          image: simplygoodsoftware/dev-pyrus-setup
          imagePullPolicy: IfNotPresent
          args:
            - --update
{{- end }}
      containers:
        - name: setup-complite
          image: simplygoodsoftware/k8s-waits
          imagePullPolicy: IfNotPresent
          command: [ "ls" ]
