{{- if not (lookup "batch/v1" "Job" .Release.Namespace "set-pyrus-setupparam") }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: &name set-pyrus-setupparam
  labels: &selector
    app: *name
  annotations:
    helm.sh/resource-policy: keep
spec:
  activeDeadlineSeconds: 1200
  template:
    metadata:
      labels: *selector
    spec:
      restartPolicy: OnFailure
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: docker-pyrus-cred
{{- end }}
      initContainers:
{{- if or (or (not .Values.database.external) $.Values.elasticsearch.internalChart) (not $.Values.logs.external)}}
        - name: depends-on
          image: {{ .Values.containersRepo.default }}/k8s-waits
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          command:
            - wait_endpoints
{{-   if not .Values.database.external }}
            - {{ .Release.Namespace }}/endpoints/pyrus-postgresql
{{-   end }}
{{-   if $.Values.elasticsearch.internalChart }}
            - {{ .Release.Namespace }}/endpoints/pyrus-elastic
{{-   end }}
{{-   if not $.Values.logs.external }}
            - {{ .Release.Namespace }}/endpoints/pyrus-logs-pgsql
{{-   end }}
{{- end }}

{{- if eq .Release.Revision 1 }}
{{-   if not (hasKey .Values.standalonePostgreSQLBackup "RESTORE_NAME")  }}
        - name: setup-create-db
          image: {{ .Values.containersRepo.default }}/{{ .Values.imageDevPrefix }}pyrus-setup:{{ .Values.tagsContainers.All }}
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          args: [
            "--create", "--skip",
            "--email", "{{ .Values.pyrusSetupParam.adminEmail }}",
            "--adminpassword",  "{{ .Values.pyrusSetupParam.adminPass }}"
            ]
          envFrom:
            - configMapRef:
                name: common-variables
{{-   end }}

{{-   range $name, $value := .Values.pyrusSetupParam.setupById }}
        - name: setup-setupbyid-{{ $name }}
          image: {{ $.Values.containersRepo.default }}/{{ $.Values.imageDevPrefix }}pyrus-setup:{{ $.Values.tagsContainers.All }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-variables
          args: ["--setup", "-id", "{{ $name }}", "-v", "{{ $value }}"]
{{-   end }}

        - name: start-change-tracking
          image: {{ .Values.containersRepo.default }}/{{ .Values.imageDevPrefix }}pyrus-setup:{{ .Values.tagsContainers.All }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-variables
          args:
            - -ct
            - --start

        - name: setup-elastic-index-it
          image: {{ .Values.containersRepo.default }}/pyrus-elastic-console:{{ .Values.tagsContainers.All }}
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: common-variables
          args:
            - -it

        - name: setup-elastic-index-in
          image: {{ .Values.containersRepo.default }}/pyrus-elastic-console:{{ .Values.tagsContainers.All }}
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: common-variables
          args:
            - -in

        - name: setup-elastic-index-ic
          image: {{ .Values.containersRepo.default }}/pyrus-elastic-console:{{ .Values.tagsContainers.All }}
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: common-variables
          args:
            - -ic

        - name: setup-elastic-index-ip
          image: {{ .Values.containersRepo.default }}/pyrus-elastic-console:{{ .Values.tagsContainers.All }}
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: common-variables
          args:
            - -ip

{{-   if hasKey .Values.standalonePostgreSQLBackup "RESTORE_NAME"  }}

        - name: setup-administrator-account
          image: {{ .Values.containersRepo.default }}/{{ .Values.imageDevPrefix }}pyrus-setup:{{ .Values.tagsContainers.All }}
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: common-variables
          args: [
            "--setadmin",
            "--email", "{{ .Values.pyrusSetupParam.adminEmail }}",
            "--adminpassword",  "{{ .Values.pyrusSetupParam.adminPass }}"
            ]

        - name: setup-elastic-index-rt
          image: {{ .Values.containersRepo.default }}/pyrus-elastic-console:{{ .Values.tagsContainers.All }}
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: common-variables
          args:
            - -rt

        - name: setup-elastic-index-wgall
          image: {{ .Values.containersRepo.default }}/pyrus-elastic-console:{{ .Values.tagsContainers.All }}
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: common-variables
          args:
            - -wgall

        - name: setup-elastic-index-wcall
          image: {{ .Values.containersRepo.default }}/pyrus-elastic-console:{{ .Values.tagsContainers.All }}
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: common-variables
          args:
            - -wcall

        - name: setup-elastic-index-wpall
          image: {{ .Values.containersRepo.default }}/pyrus-elastic-console:{{ .Values.tagsContainers.All }}
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: common-variables
          args:
            - -wpall

        - name: setup-elastic-index-wnall
          image: {{ .Values.containersRepo.default }}/pyrus-elastic-console:{{ .Values.tagsContainers.All }}
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: common-variables
          args:
            - -wnall
{{-   end }}
{{-   if .Values.pyrusSetupParam.s3 }}
{{      if (semverCompare "<1.12.1" $.Values.tagsContainers.All) }}
        - name: setup-s3-storrage-1
          image: {{ .Values.containersRepo.default }}/{{ .Values.imageDevPrefix }}pyrus-setup:{{ .Values.tagsContainers.All }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-variables
          args: [ "--setup", "-id", "9900151", "-v", "{{ .Values.pyrusSetupParam.s3.keyId }}"]

        - name: setup-s3-storrage-2
          image: {{ .Values.containersRepo.default }}/{{ .Values.imageDevPrefix }}pyrus-setup:{{ .Values.tagsContainers.All }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-variables
          args: ["--setup", "-id", "9900152", "-v", "{{ .Values.pyrusSetupParam.s3.secretKey }}"]

        - name: setup-s3-storrage-3
          image: {{ .Values.containersRepo.default }}/{{ .Values.imageDevPrefix }}pyrus-setup:{{ .Values.tagsContainers.All }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-variables
          args: ["--setup", "-id", "9900153", "-v", "{{ .Values.pyrusSetupParam.s3.buket }}"]

        - name: setup-s3-storrage-4
          image: {{ .Values.containersRepo.default }}/{{ .Values.imageDevPrefix }}pyrus-setup:{{ .Values.tagsContainers.All }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-variables
          args: [ "--setup", "-id", "9910002", "-v", "{{ .Values.pyrusSetupParam.s3.S3_BLOB_STORAGE_ENDPOINT }}" ]

        - name: setup-s3-storrage-5
          image: {{ .Values.containersRepo.default }}/{{ .Values.imageDevPrefix }}pyrus-setup:{{ .Values.tagsContainers.All }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-variables
          args: [ "--setup", "-id", "9910004", "-v", "true"]
{{-     else }}
        - name: setup-s3-storrage-1210
          image: {{ .Values.containersRepo.default }}/{{ .Values.imageDevPrefix }}pyrus-setup:{{ .Values.tagsContainers.All }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-variables
          args: 
            - --configure-s3
            - --accessKey
            - {{ .Values.pyrusSetupParam.s3.keyId }}
            - --secretKey
            - {{ .Values.pyrusSetupParam.s3.secretKey }}
            - --bucket
            - {{ .Values.pyrusSetupParam.s3.buket }}
{{-         if .Values.pyrusSetupParam.s3.storageType }}
{{-           $storageTypes := list "Aws" "MinIo" "Azure" "Mts" "VkCloud" }}
{{-           if not (has .Values.pyrusSetupParam.s3.storageType $storageTypes)  }}
{{-             fail "\n\n! BREAK ! .Values.pyrusSetupParam.s3.storageType must be in 'Aws', 'MinIo', 'Azure', 'Mts', 'VkCloud'\n" }}
{{-           end }}
            - --storageType 
            - {{ .Values.pyrusSetupParam.s3.storageType }}
{{-         end }}
            - --endpointUrl
            - {{ .Values.pyrusSetupParam.s3.S3_BLOB_STORAGE_ENDPOINT }}
{{-     end }}
{{-   end }}

{{-  if (semverCompare ">1.12.0" $.Values.tagsContainers.All) }}
{{-    if not .Values.pyrusSetupParam.s3 }}
{{-      fail "\n\n! BREAK ! NEED to define .Values.pyrusSetupParam.s3\n" }}
{{-    end }}
{{-  end }}


        - name: setup-license-variables
          image: {{ .Values.containersRepo.default }}/{{ .Values.imageDevPrefix }}pyrus-setup:{{ .Values.tagsContainers.All }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-variables
          args: ["--setup", "-id", "100000", "-v", "{{ .Values.pyrusSetupParam.license }}"]

        - name: setup-domain-name
          image: {{ .Values.containersRepo.default }}/{{ .Values.imageDevPrefix }}pyrus-setup:{{ .Values.tagsContainers.All }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-variables
          args: ["--setup", "-id", "100001", "-v", "{{ first (first (index .Values "values-ingress-dir").tls).hosts }}"]

{{-   if .Values.imageDevPrefix }}
        - name: update-database-for-dev
          image: {{ .Values.containersRepo.default }}/dev-pyrus-setup:{{ .Values.tagsContainers.All }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-variables
          args:
            - --update
{{-   end }}

{{- end }}
      containers:
        - name: setup-complite
          image: {{ .Values.containersRepo.default }}/k8s-waits
          imagePullPolicy: IfNotPresent
          command: [ "ls" ]
{{- end }}

