{{- if not (lookup "batch/v1" "Job" .Release.Namespace "set-pyrus-setupparam") }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: &name set-pyrus-setupparam
  labels: &selector
    app: *name
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-weight: "-5"
spec:
  template:
    metadata:
      labels: *selector
    spec:
      restartPolicy: OnFailure
      containers:
        - name: setup-complite
          image: {{ .Values.containersRepo.default }}/k8s-waits
          imagePullPolicy: IfNotPresent
          command: [ "ls" ]
{{- end }}
