{{- $cname := "pyrus-smtp" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name {{ $cname }}
  labels: &selector
    app: *name
spec:
  selector:
    matchLabels:
      app: *name
  replicas: {{ (index $.Values.countStrategy $cname).replicas | default 0 }}
  template:
    metadata:
      labels:
        app: *name
    spec:
      containers:
        - name: *name
          image: namshi/smtp
          {{- if hasKey $.Values.env $cname }}
          env:
            {{- with (index $.Values.env $cname) }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
