{{- $rl := .Release }}
{{- $vl := .Values }}
{{- range $secretName, $svl := $vl.webSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ index $svl "tls.crt" | b64enc }}
  tls.key: {{ index $svl "tls.key" | b64enc }}
  tls.pem: {{ index $svl "tls.pem" | b64enc }}
{{- end }}
