apiVersion: v1
kind: Service
metadata:
  name: pyrus-elastic
spec:
  clusterIP: None
  internalTrafficPolicy: Cluster
  ports:
  - name: elasticsearch
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elasticsearch-master
---
{{- if ne $.Release.Name "pyrus" }}
apiVersion: v1
kind: Service
metadata:
  name: pyrus-nats
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: nats-clients
    port: 4222
    protocol: TCP
  selector:
    app.kubernetes.io/name: nats
{{- end }}
---
{{- if not .Values.postgresql.enabledHA }}
{{- if not .Values.database.external }}
apiVersion: v1
kind: Service
metadata:
  name: pyrus-postgresql
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
  selector:
    app: pyrus-postgresql
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: pyrus-logs-pgsql
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
  selector:
    app: pyrus-logs-pgsql
