{{- define "pyrus-lib.secretRef" }}
{{-   $TARGET         := "secretRef" }}
{{-   $Defaults       := index $.Values "defaults" }}
{{-   $Defaults       := index $.Values  "defaults"    | default dict }}
{{-   $DefaultsTARGET := index $Defaults $TARGET       | default dict }}
{{-   range $mountPoint, $mountValues := $DefaultsTARGET }}
---
apiVersion: v1
kind: Secret
metadata:
  name: defaults-{{ $mountPoint | replace "/" "-" | replace "." "-" | replace "_" "-" }}
type: Opaque
data:
{{-     range $fileName, $fileValue := $mountValues }}
  {{ $fileName }}: | {{- $fileValue | b64enc | nindent 4 }}
{{-     end }}
{{-   end }}
{{- end }}

{{- include "pyrus-lib.secretRef" $ }}
